apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: no-resource-requests
spec:
  ports:
    - port: 443
  selector:
    app: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: no-resource-requests
spec:
  selector:
    matchLabels:
      app: webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: webhook
      namespace: no-resource-requests
    spec:
      serviceAccount: webhook
      containers:
        - name: webhook
          image: github.com/projectriff/no-resource-requests-webhook/cmd/webhook
          args: ["--debug"]
          ports:
            - containerPort: 443
              name: server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
